// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 762710f0f0c99651 "UNHINGED (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-W6FT4636.js";
import { routes } from "./chunks/chunk-VGZ5GRAF.js";

// virtual:button-unfilled
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nW3xbVn95Kr5rj6Ghqnd/ePcZtSClWsRCJwIYIBnI/QzZ53Qx6c.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	l6HiRIyEJ: {
		hover: true,
	},
};
var cycleOrder = ["l6HiRIyEJ"];
var serializationHash = "framer-WMeuw";
var variantClassNames = {
	l6HiRIyEJ: "framer-v-1bt08ea",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, title, width, ...props }) => {
	var _ref;
	return {
		...props,
		ny232fV0M:
			(_ref = title !== null && title !== void 0 ? title : props.ny232fV0M) !==
				null && _ref !== void 0
				? _ref
				: "Get template",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ny232fV0M,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "l6HiRIyEJ",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<Link
					href={
						"https://viflordesign.lemonsqueezy.com/checkout/buy/a8209f56-5fb7-44f9-9910-69ec5ca17861"
					}
					openInNewTab={true}
				>
					<motion.a
						{...restProps}
						animate={variants}
						className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-1bt08ea", className2, classNames)} framer-1l9o5qq`}
						data-framer-name={"Variant 1"}
						initial={variant}
						layoutDependency={layoutDependency}
						layoutId={"l6HiRIyEJ"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 37,
							borderBottomRightRadius: 37,
							borderTopLeftRadius: 37,
							borderTopRightRadius: 37,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"l6HiRIyEJ-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-13laxln"}
							layoutDependency={layoutDependency}
							layoutId={"e_zSm5we_"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-232ed45b-8622-40fa-9eba-51c55023a20d, rgb(140, 44, 165))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={ny232fV0M}
							variants={{
								"l6HiRIyEJ-hover": {
									"--extracted-r6o4lv":
										"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) ",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									"l6HiRIyEJ-hover": {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1wuumuu"}
													data-styles-preset={"kRKaKn3c7"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) )",
													}}
												>
													{"Get template"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1wuumuu"}
									data-styles-preset={"kRKaKn3c7"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-232ed45b-8622-40fa-9eba-51c55023a20d, rgb(140, 44, 165)))",
									}}
								>
									{"Boost your brand"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<SVG
							className={"framer-84q6rw"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"w1pm2Glto"}
							opacity={1}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 53 53"><path d="M 0 35.074 L 35.192 0 L 35.192 12 L 35.192 0 L 23.192 0" transform="translate(9.247 9.005) rotate(45 17.596 17.537)" fill="transparent" stroke-width="1.5" stroke="var(--token-232ed45b-8622-40fa-9eba-51c55023a20d, rgb(140, 44, 165))" stroke-linecap="round" stroke-linejoin="round"></path></svg>'
							}
							svgContentId={3020880490}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									"l6HiRIyEJ-hover": {
										svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 53 53"><path d="M 0 35.074 L 35.192 0 L 35.192 12 L 35.192 0 L 23.192 0" transform="translate(9.247 9.005) rotate(45 17.596 17.537)" fill="transparent" stroke-width="1.5" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;100 White&quot;} */" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
										svgContentId: 1583116516,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.a>
				</Link>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-WMeuw[data-border="true"]::after, .framer-WMeuw [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WMeuw.framer-1l9o5qq, .framer-WMeuw .framer-1l9o5qq { display: block; }",
	".framer-WMeuw.framer-1bt08ea { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 40px; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: auto; }",
	".framer-WMeuw .framer-13laxln { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-WMeuw .framer-84q6rw { flex: none; height: 53px; position: relative; width: 53px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-WMeuw.framer-1bt08ea { gap: 0px; } .framer-WMeuw.framer-1bt08ea > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-WMeuw.framer-1bt08ea > :first-child { margin-left: 0px; } .framer-WMeuw.framer-1bt08ea > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerQzZ53Qx6c = withCSS(Component, css2, "framer-WMeuw");
var stdin_default = FramerQzZ53Qx6c;
FramerQzZ53Qx6c.displayName = "Button (Unfilled)";
FramerQzZ53Qx6c.defaultProps = {
	height: 40,
	width: 184,
};
addPropertyControls(FramerQzZ53Qx6c, {
	ny232fV0M: {
		defaultValue: "Get template",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(FramerQzZ53Qx6c, [...fonts]);

// virtual:button-unfilled
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonUnfilledFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_unfilled_default = ComponentWithRoot;
export { button_unfilled_default as default };
