// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 762710f0f0c99651 "UNHINGED (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Mobile' // Variant
 * cTA?: string // CTA
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-W6FT4636.js";
import { routes } from "./chunks/chunk-VGZ5GRAF.js";

// virtual:button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mEfue6848bT7uHKaKAvA/ycEaKjVCaAUapzjgTXKO/jBGIqn2mr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	dl5AfPGN9: {
		hover: true,
	},
	gF_65Ml1c: {
		hover: true,
	},
	uGFcAoBjt: {
		hover: true,
	},
};
var cycleOrder = ["dl5AfPGN9", "gF_65Ml1c", "uGFcAoBjt"];
var serializationHash = "framer-JhJBk";
var variantClassNames = {
	dl5AfPGN9: "framer-v-1e8jjh0",
	gF_65Ml1c: "framer-v-vvpttt",
	uGFcAoBjt: "framer-v-1e9a1bt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "dl5AfPGN9",
	"Variant 2": "gF_65Ml1c",
	Mobile: "uGFcAoBjt",
};
var getProps = ({ cTA, height, id, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		qf8EYhhDy:
			(_ref = cTA !== null && cTA !== void 0 ? cTA : props.qf8EYhhDy) !==
				null && _ref !== void 0
				? _ref
				: "Get template",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "dl5AfPGN9",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		qf8EYhhDy,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "dl5AfPGN9",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["gF_65Ml1c-hover", "uGFcAoBjt-hover"].includes(gestureVariant))
			return false;
		if (["gF_65Ml1c", "uGFcAoBjt"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition}>
					<Link
						href={
							"https://viflordesign.lemonsqueezy.com/checkout/buy/a8209f56-5fb7-44f9-9910-69ec5ca17861"
						}
						openInNewTab={true}
					>
						<motion.a
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-1e8jjh0", className2, classNames)} framer-i7g904`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"dl5AfPGN9"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								background:
									"linear-gradient(180deg, rgb(222, 70, 242) 0%, #8C2CA5 100%)",
								borderBottomLeftRadius: 37,
								borderBottomRightRadius: 37,
								borderTopLeftRadius: 37,
								borderTopRightRadius: 37,
								...style,
							}}
							variants={{
								"dl5AfPGN9-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										'var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {"name":"90 Black"} */',
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									background:
										'linear-gradient(180deg, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 0%, rgb(255, 255, 255) 100%)',
								},
								"gF_65Ml1c-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										'var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {"name":"90 Black"} */',
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									background:
										'linear-gradient(180deg, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 0%, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 100%)',
								},
								"uGFcAoBjt-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										'var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {"name":"90 Black"} */',
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									background:
										'linear-gradient(180deg, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 0%, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 100%)',
								},
								gF_65Ml1c: {
									background:
										"linear-gradient(180deg, rgb(222, 70, 242) 0%, rgb(140, 44, 165) 100%)",
								},
								uGFcAoBjt: {
									background:
										"linear-gradient(180deg, rgb(222, 70, 242) 0%, rgb(140, 44, 165) 100%)",
								},
							}}
							{...addPropertyOverrides(
								{
									"dl5AfPGN9-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									"gF_65Ml1c-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									"uGFcAoBjt-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									gF_65Ml1c: {
										"data-framer-name": "Variant 2",
									},
									uGFcAoBjt: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-10iugvl"}
								layoutDependency={layoutDependency}
								layoutId={"vde_q4kmo"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={qf8EYhhDy}
								variants={{
									"dl5AfPGN9-hover": {
										"--extracted-r6o4lv":
											"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) ",
									},
									"gF_65Ml1c-hover": {
										"--extracted-r6o4lv":
											"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) ",
									},
									"uGFcAoBjt-hover": {
										"--extracted-r6o4lv":
											"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) ",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"dl5AfPGN9-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wuumuu"}
														data-styles-preset={"kRKaKn3c7"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) )",
														}}
													>
														{"Get template"}
													</motion.p>
												</React.Fragment>
											),
										},
										"gF_65Ml1c-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wuumuu"}
														data-styles-preset={"kRKaKn3c7"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) )",
														}}
													>
														{"Get template"}
													</motion.p>
												</React.Fragment>
											),
										},
										"uGFcAoBjt-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wuumuu"}
														data-styles-preset={"kRKaKn3c7"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) )",
														}}
													>
														{"Get template"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1wuumuu"}
										data-styles-preset={"kRKaKn3c7"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
										}}
									>
										{"Boost your brand"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<SVG
									className={"framer-1fsy85x"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"e0GbT2vHR-shape"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 53 53"><path d="M 0 35.074 L 35.192 0 L 35.192 12 L 35.192 0 L 23.192 0" transform="translate(9.247 9.005) rotate(45 17.596 17.537)" fill="transparent" stroke-width="1.5" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round" stroke-linejoin="round"></path></svg>'
									}
									svgContentId={2508863456}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"dl5AfPGN9-hover": {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 53 53"><path d="M 0 35.074 L 35.192 0 L 35.192 12 L 35.192 0 L 23.192 0" transform="translate(9.247 9.005) rotate(45 17.596 17.537)" fill="transparent" stroke-width="1.5" stroke="var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {&quot;name&quot;:&quot;90 Black&quot;} */" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
												svgContentId: 1405563195,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-JhJBk[data-border="true"]::after, .framer-JhJBk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JhJBk.framer-i7g904, .framer-JhJBk .framer-i7g904 { display: block; }",
	".framer-JhJBk.framer-1e8jjh0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 40px; justify-content: center; overflow: visible; padding: 16px 32px 16px 32px; position: relative; text-decoration: none; width: auto; }",
	".framer-JhJBk .framer-10iugvl { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-JhJBk .framer-1fsy85x { flex: none; height: 53px; position: relative; width: 53px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-JhJBk.framer-1e8jjh0 { gap: 0px; } .framer-JhJBk.framer-1e8jjh0 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-JhJBk.framer-1e8jjh0 > :first-child { margin-left: 0px; } .framer-JhJBk.framer-1e8jjh0 > :last-child { margin-right: 0px; } }",
	".framer-JhJBk.framer-v-1e9a1bt.framer-1e8jjh0 { height: 30px; padding: 16px 16px 16px 16px; }",
	...css,
];
var FramerjBGIqn2mr = withCSS(Component, css2, "framer-JhJBk");
var stdin_default = FramerjBGIqn2mr;
FramerjBGIqn2mr.displayName = "Button";
FramerjBGIqn2mr.defaultProps = {
	height: 40,
	width: 248,
};
addPropertyControls(FramerjBGIqn2mr, {
	variant: {
		options: ["dl5AfPGN9", "gF_65Ml1c", "uGFcAoBjt"],
		optionTitles: ["Variant 1", "Variant 2", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	qf8EYhhDy: {
		defaultValue: "Get template",
		displayTextArea: false,
		title: "CTA",
		type: ControlType.String,
	},
});
addFonts(FramerjBGIqn2mr, [...fonts]);

// virtual:button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "dl5AfPGN9",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export { button_default as default };
