// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 762710f0f0c99651 "UNHINGED (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Closed' | 'Open' // Variant
 * question?: string // Question
 * answer?: string // Answer
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-G2TO6BN5.js";
import { routes } from "./chunks/chunk-VGZ5GRAF.js";

// virtual:fa-qs
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8cHIetQfikTB62OgK3O3/cKgCbsWlTxhNV1SQv5kb/YTd8cyPH7.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useActiveVariantCallback,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["cQ78VvRBS", "e5ZiqFQgj"];
var serializationHash = "framer-db4QW";
var variantClassNames = {
	cQ78VvRBS: "framer-v-7g9ku9",
	e5ZiqFQgj: "framer-v-1u262kx",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 40,
		delay: 0,
		mass: 1,
		stiffness: 400,
		type: "spring",
	},
	e5ZiqFQgj: {
		delay: 0,
		duration: 0.5,
		ease: [0.12, 0.23, 0.5, 1],
		type: "tween",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Closed: "cQ78VvRBS",
	Open: "e5ZiqFQgj",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1, _ref2;
	return {
		...props,
		T8rQFvSBR:
			(_ref =
				answer !== null && answer !== void 0 ? answer : props.T8rQFvSBR) !==
				null && _ref !== void 0
				? _ref
				: "Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "cQ78VvRBS",
		W88zB8mIG:
			(_ref2 =
				question !== null && question !== void 0
					? question
					: props.W88zB8mIG) !== null && _ref2 !== void 0
				? _ref2
				: "What is Framer?",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		W88zB8mIG,
		T8rQFvSBR,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cQ78VvRBS",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapqebn2z = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		await delay(() => setVariant("e5ZiqFQgj"), 200);
	});
	const onTap15xxojf = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("e5ZiqFQgj"), 100);
	});
	const onTap11t60lk = activeVariantCallback(async (...args) => {
		setVariant("cQ78VvRBS");
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "e5ZiqFQgj") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-7g9ku9",
						className2,
						classNames,
					)}
					data-framer-name={"Closed"}
					data-highlight={true}
					initial={variant}
					layoutDependency={layoutDependency}
					layoutId={"cQ78VvRBS"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={onTapqebn2z}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							e5ZiqFQgj: {
								"data-framer-name": "Open",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						className={"framer-x8376u"}
						data-framer-name={"Question"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"Fn2FhBWzw"}
						onTap={onTap15xxojf}
						{...addPropertyOverrides(
							{
								e5ZiqFQgj: {
									onTap: onTap11t60lk,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-mr5290"}
							layoutDependency={layoutDependency}
							layoutId={"C5zjku1aI"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) ",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={W88zB8mIG}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-15zjald"}
									data-styles-preset={"Ge7bltu5p"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) )",
									}}
								>
									{"What is Framer?"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<SVG
							className={"framer-aunxny"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"ZzBUS4HwL-shape"}
							opacity={1}
							radius={{
								bottomLeft: 5,
								bottomRight: 5,
								topLeft: 5,
								topRight: 5,
							}}
							style={{
								borderBottomLeftRadius: 5,
								borderBottomRightRadius: 5,
								borderTopLeftRadius: 5,
								borderTopRightRadius: 5,
							}}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 19 11"><path d="M 1.5 1.214 L 9.5 9.214 L 17.5 1.214" fill="transparent" stroke-width="2" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;100 White&quot;} */" stroke-linecap="round" stroke-linejoin="round"></path></svg>'
							}
							svgContentId={1291819916}
							withExternalLayout={true}
						/>
					</motion.div>
					{isDisplayed() && (
						<motion.div
							className={"framer-1iurao8"}
							data-framer-name={"Answer"}
							layoutDependency={layoutDependency}
							layoutId={"FdjcZwUFD"}
							style={{
								opacity: 0,
							}}
							variants={{
								e5ZiqFQgj: {
									opacity: 1,
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1uviwgk"}
								layoutDependency={layoutDependency}
								layoutId={"rXe7BkyE8"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) ",
									opacity: 0.7,
								}}
								text={T8rQFvSBR}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-15zjald"}
										data-styles-preset={"Ge7bltu5p"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) )",
										}}
									>
										{
											"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					)}
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-db4QW[data-border="true"]::after, .framer-db4QW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-db4QW.framer-10a23jj, .framer-db4QW .framer-10a23jj { display: block; }",
	".framer-db4QW.framer-7g9ku9 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 400px; }",
	".framer-db4QW .framer-x8376u { -webkit-user-select: none; align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 0px 20px 0px; position: relative; user-select: none; width: 100%; }",
	".framer-db4QW .framer-mr5290 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-db4QW .framer-aunxny { flex: none; height: 11px; position: relative; width: 19px; }",
	".framer-db4QW .framer-1iurao8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 20px 20px 0px; position: relative; width: 100%; }",
	".framer-db4QW .framer-1uviwgk { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-db4QW.framer-7g9ku9, .framer-db4QW .framer-x8376u, .framer-db4QW .framer-1iurao8 { gap: 0px; } .framer-db4QW.framer-7g9ku9 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-db4QW.framer-7g9ku9 > :first-child, .framer-db4QW .framer-1iurao8 > :first-child { margin-top: 0px; } .framer-db4QW.framer-7g9ku9 > :last-child, .framer-db4QW .framer-1iurao8 > :last-child { margin-bottom: 0px; } .framer-db4QW .framer-x8376u > * { margin: 0px; margin-left: calc(24px / 2); margin-right: calc(24px / 2); } .framer-db4QW .framer-x8376u > :first-child { margin-left: 0px; } .framer-db4QW .framer-x8376u > :last-child { margin-right: 0px; } .framer-db4QW .framer-1iurao8 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	...css,
];
var FramerYTd8cyPH7 = withCSS(Component, css2, "framer-db4QW");
var stdin_default = FramerYTd8cyPH7;
FramerYTd8cyPH7.displayName = "FAQs";
FramerYTd8cyPH7.defaultProps = {
	height: 64,
	width: 400,
};
addPropertyControls(FramerYTd8cyPH7, {
	variant: {
		options: ["cQ78VvRBS", "e5ZiqFQgj"],
		optionTitles: ["Closed", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	W88zB8mIG: {
		defaultValue: "What is Framer?",
		displayTextArea: true,
		title: "Question",
		type: ControlType.String,
	},
	T8rQFvSBR: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.",
		displayTextArea: true,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(FramerYTd8cyPH7, [...fonts]);

// virtual:fa-qs
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "cQ78VvRBS",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaQsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var fa_qs_default = ComponentWithRoot;
export { fa_qs_default as default };
