// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 762710f0f0c99651 "UNHINGED (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-CCFKFPA2.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-G2TO6BN5.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-AKPG7R6U.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-FAVGGUSS.js";
import { routes } from "./chunks/chunk-VGZ5GRAF.js";

// virtual:footer-dark
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gh9Cz7c2SlQG7G32uE4e/n2FGgF1vQpEWpe2cFHqV/IIGMd7Ixk.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFonts,
	Link,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/oWVHHLIj4Q7woeIlKzbt/UIXK1WcUX02tYQTouHsC/Input.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCallback, useState } from "react";
import {
	addPropertyControls,
	ControlType,
	withCSS,
	useRouter,
	inferInitialRouteFromPath,
} from "unframer";
import { motion, useAnimationControls } from "unframer";
var emailRegex =
	/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
var mailchimpRegex = /^https?:\/\/([^\/]+)[^\?]+\??(.+)$/;
var validateEmail = (email) => {
	return emailRegex.test(String(email).toLowerCase());
};
var parseMailChimpUrl = (url) => {
	var _url_replace_match;
	const [, domain, parameters] =
		(_url_replace_match = url.replace("&amp;", "&").match(mailchimpRegex)) !==
			null && _url_replace_match !== void 0
			? _url_replace_match
			: [null, null, null];
	return [domain, parameters ? new URLSearchParams(parameters) : null];
};
function safeURL(url) {
	console.log(url);
	try {
		new URL(url);
		return url;
	} catch {
		try {
			new URL(`https://${url}`);
			return `https://${url}`;
		} catch {}
	}
	return void 0;
}
function isInternalURL(href) {
	if (href === void 0) return false;
	if (href.startsWith("#") || href.startsWith("/") || href.startsWith("."))
		return true;
	return false;
}
var VERSION = "v1";
var Input = withCSS(
	function Input2({
		service,
		redirectAs,
		mailchimpURL,
		loopsID,
		loopsUserGroup,
		formsparkID,
		getwaitlistAPI,
		input,
		button,
		font,
		layout,
		link,
		gap,
		style,
		onSubmit,
	}) {
		const [email, setEmail] = useState("");
		const [isError, setError] = useState(false);
		const [isLoading, setLoading] = useState(false);
		const [isFocus, setFocus] = useState(false);
		const {
			paddingPerSide,
			paddingTop,
			paddingRight,
			paddingBottom,
			paddingLeft,
			padding,
			borderRadius,
			borderObject,
			focusObject,
			shadowObject,
			height,
			fixedHeight,
		} = input;
		const {
			buttonPaddingPerSide,
			buttonPaddingTop,
			buttonPaddingRight,
			buttonPaddingBottom,
			buttonPaddingLeft,
			buttonPadding,
		} = button;
		const paddingValue = paddingPerSide
			? `${paddingTop}px ${button.isDocked ? paddingRight + button.widthWhenDocked : paddingRight}px ${paddingBottom}px ${paddingLeft}px`
			: `${padding}px ${button.isDocked ? padding + button.widthWhenDocked : padding}px ${padding}px ${padding}px`;
		const buttonPaddingValue = buttonPaddingPerSide
			? `${button.isDocked ? 0 : buttonPaddingTop}px ${buttonPaddingRight}px ${button.isDocked ? 0 : buttonPaddingBottom}px ${buttonPaddingLeft}px`
			: `${button.isDocked ? 0 : buttonPadding}px ${buttonPadding}px ${button.isDocked ? 0 : buttonPadding}px ${buttonPadding}px`;
		const router = useRouter();
		const onSuccess = () => {
			setLoading(false);
			setFocus(false);
			setEmail("");
			if (redirectAs === "link" && link && !isError) {
				const [path, hash] = link.split("#");
				const { routeId, pathVariables } = inferInitialRouteFromPath(
					router.routes,
					path,
				);
				if (routeId) {
					router.navigate(routeId, hash, pathVariables);
				}
				if (!isInternalURL(link)) {
					const url = safeURL(link);
					if (url) window.open(url, "_blank");
				}
			}
		};
		const validateForm = useCallback(
			(email2) => {
				if (email2 === "" || !validateEmail(email2)) {
					setError(true);
					formControls.start("error");
					return false;
				}
				return true;
			},
			[validateEmail],
		);
		const handleChange = useCallback((event) => {
			setError(false);
			setEmail(event.target.value);
		}, []);
		const handleFocus = useCallback((event) => {
			setFocus(true);
		}, []);
		const handleBlur = useCallback((event) => {
			setFocus(false);
			setError(false);
		}, []);
		const handleSubmit = useCallback(
			(event) => {
				event.preventDefault();
				if (isLoading) return;
				setLoading(true);
				if (service === "mailchimp") {
					const [domain, parameters] = parseMailChimpUrl(mailchimpURL);
					if (!validateForm(email) || !domain || !parameters) {
						setLoading(false);
						return;
					}
					parameters.set("MERGE0", email);
					fetch(`https://${domain}/subscribe/post`, {
						method: "POST",
						mode: "no-cors",
						headers: {
							"Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
						},
						body: parameters.toString(),
					})
						.then((response) => {
							onSuccess();
							if (redirectAs === "overlay")
								onSubmit === null || onSubmit === void 0 ? void 0 : onSubmit();
						})
						.catch((error) => {
							console.error(error);
							setLoading(false);
							setError(true);
							formControls.start("error");
						});
				}
				if (service === "loops") {
					if (!validateForm(email)) {
						setLoading(false);
						return;
					}
					const emailBody = `email=${encodeURIComponent(email)}`;
					const userGroupBody = `userGroup=${encodeURIComponent(loopsUserGroup)}`;
					const hasUserGroup = !!loopsUserGroup && loopsUserGroup !== " ";
					const formBody = hasUserGroup
						? emailBody + "&" + userGroupBody
						: emailBody;
					fetch(`https://app.loops.so/api/newsletter-form/${loopsID}`, {
						method: "POST",
						mode: "no-cors",
						headers: {
							"Content-Type": "application/x-www-form-urlencoded",
						},
						body: formBody,
					})
						.then(() => {
							onSuccess();
							if (redirectAs === "overlay")
								onSubmit === null || onSubmit === void 0 ? void 0 : onSubmit();
						})
						.catch((error) => {
							console.error(error);
							setLoading(false);
							setError(true);
							formControls.start("error");
						});
				}
				if (service === "formspark") {
					if (!validateForm(email)) {
						setLoading(false);
						return;
					}
					const data = new FormData(event.target);
					const entries = Object.fromEntries(data.entries());
					fetch(`https://api.formspark.io/${formsparkID}`, {
						method: "POST",
						headers: {
							"Content-Type": "application/json",
							Accept: "application/json",
						},
						body: JSON.stringify(entries),
					})
						.then(() => {
							onSuccess();
							onSubmit === null || onSubmit === void 0 ? void 0 : onSubmit();
						})
						.catch((error) => {
							console.error(error);
							setLoading(false);
							setError(true);
							formControls.start("error");
						});
				}
				if (service === "getwaitlist") {
					if (!validateForm(email)) {
						setLoading(false);
						return;
					}
					const formData = new FormData(event.target);
					const data = Object.fromEntries(formData.entries());
					data.referral_link = document.URL;
					fetch(
						`https://api.getwaitlist.com/api/v1
/waiter/`,
						{
							method: "POST",
							headers: {
								"Content-Type": "application/json",
								Accept: "application/json",
							},
							body: JSON.stringify(data),
						},
					)
						.then(() => {
							onSuccess();
							if (redirectAs === "overlay")
								onSubmit === null || onSubmit === void 0 ? void 0 : onSubmit();
						})
						.catch((error) => {
							console.error(error);
							setLoading(false);
							setError(true);
							formControls.start("error");
						});
				}
			},
			[mailchimpURL, formsparkID, email, onSubmit, validateForm, isLoading],
		);
		const formControls = useAnimationControls();
		const focusStylesFrom = input.focusObject
			? `inset 0 0 0 ${focusObject.focusWidthFrom}px ${focusObject.focusColor}`
			: null;
		const focusStylesTo = input.focusObject
			? `inset 0 0 0 ${focusObject.focusWidthTo}px ${focusObject.focusColor}`
			: null;
		const shadowStyles = input.shadowObject
			? `${shadowObject.shadowX}px ${shadowObject.shadowY}px ${shadowObject.shadowBlur}px ${shadowObject.shadowColor}`
			: null;
		const borderStyles = input.borderObject
			? `inset 0 0 0 ${borderObject.borderWidth}px ${borderObject.borderColor}`
			: null;
		const formVariants = {
			default: {
				x: 0,
			},
			error: {
				x: [0, -4, 4, 0],
				transition: {
					duration: 0.2,
				},
			},
		};
		const inputVariants = {
			default: {
				boxShadow: dynamicBoxShadow(
					focusStylesFrom,
					shadowStyles,
					borderStyles,
				),
			},
			focused: {
				boxShadow: dynamicBoxShadow(focusStylesTo, shadowStyles, borderStyles),
			},
		};
		return (
			<motion.div
				style={{
					...style,
					...containerStyles,
					"--framer-custom-placeholder-color": input.placeholderColor,
				}}
				variants={formVariants}
				animate={formControls}
			>
				<form
					style={{
						width: "100%",
						height: "auto",
						display: "flex",
						position: "relative",
						flexDirection: layout === "vertical" ? "column" : "row",
						color: button.color,
						gap: button.isDocked ? 0 : gap,
					}}
					onSubmit={handleSubmit}
					method={"POST"}
				>
					{service === "getwaitlist" && (
						<input type={"hidden"} name={"api_key"} value={getwaitlistAPI} />
					)}
					<motion.input
						type={"email"}
						name={"email"}
						placeholder={input.placeholder}
						value={email}
						className={`${VERSION} framer-custom-input`}
						onChange={handleChange}
						onFocus={handleFocus}
						onBlur={handleBlur}
						autoComplete={"off"}
						autoCapitalize={"off"}
						autoCorrect={"off"}
						spellCheck={"false"}
						style={{
							...defaultStyle,
							padding: paddingValue,
							borderRadius,
							fontSize: 16,
							...font,
							background: input.fill,
							height: height ? "auto" : fixedHeight,
							color: input.color,
							boxShadow: dynamicBoxShadow(
								focusStylesFrom,
								shadowStyles,
								borderStyles,
							),
						}}
						variants={inputVariants}
						initial={false}
						animate={isFocus ? "focused" : "default"}
						transition={{
							duration: 0.3,
						}}
						data-1p-ignore={true}
					/>
					{!button.shouldAppear && isLoading && (
						<Spinner
							shouldAppear={button.shouldAppear}
							paddingPerSide={paddingPerSide}
							paddingTop={paddingTop}
							paddingRight={paddingRight}
							padding={padding}
							color={input.color}
						/>
					)}
					{button.shouldAppear && (
						<div
							style={{
								position: button.isDocked ? "absolute" : "relative",
								top: button.isDocked ? button.insetWhenDocked : 0,
								right: button.isDocked ? button.insetWhenDocked : 0,
								bottom: button.isDocked ? button.insetWhenDocked : 0,
							}}
						>
							<motion.input
								type={"submit"}
								value={button.label}
								style={{
									...defaultStyle,
									width: button.isDocked ? button.widthWhenDocked : "100%",
									height: height ? "100%" : fixedHeight,
									cursor: "pointer",
									padding: buttonPaddingValue,
									borderRadius: button.isDocked
										? borderRadius - button.insetWhenDocked
										: borderRadius,
									// fontWeight: button.fontWeight,
									fontSize: 16,
									...button.buttonFont,
									background: button.fill,
									color: button.color,
									zIndex: 1,
									boxShadow: getButtonShadow(button),
								}}
							/>
							{isLoading && (
								<div
									style={{
										borderRadius: button.isDocked
											? borderRadius - button.insetWhenDocked
											: borderRadius,
										position: "absolute",
										display: "flex",
										justifyContent: "center",
										alignItems: "center",
										width: "100%",
										height: "100%",
										inset: 0,
										zIndex: 2,
										color: button.color,
										background: button.fill,
									}}
								>
									<Spinner color={button.color} />
								</div>
							)}
						</div>
					)}
				</form>
			</motion.div>
		);
	},
	[
		`.${VERSION}.framer-custom-input::placeholder { color: var(--framer-custom-placeholder-color) !important; }`,
	],
);
var Spinner = (props) => {
	const noButtonStyles = !props.shouldAppear
		? {
				position: "absolute",
				top: `calc(50% - 8px)`,
				right: props.paddingPerSide ? props.paddingRight : props.padding,
			}
		: {};
	return (
		<motion.div
			style={{
				height: 16,
				width: 16,
				...noButtonStyles,
			}}
			initial={{
				rotate: 0,
			}}
			animate={{
				rotate: 360,
			}}
			transition={{
				duration: 1,
				repeat: Infinity,
			}}
		>
			<motion.div
				initial={{
					scale: 0,
				}}
				animate={{
					scale: 1,
				}}
			>
				<svg
					xmlns={"http://www.w3.org/2000/svg"}
					width={"16"}
					height={"16"}
					style={{
						fill: "currentColor",
						color: props.color,
					}}
				>
					<path
						d={
							"M 8 0 C 3.582 0 0 3.582 0 8 C 0 12.419 3.582 16 8 16 C 12.418 16 16 12.419 16 8 C 15.999 3.582 12.418 0 8 0 Z M 8 14 C 4.687 14 2 11.314 2 8 C 2 4.687 4.687 2 8 2 C 11.314 2 14 4.687 14 8 C 14 11.314 11.314 14 8 14 Z"
						}
						fill={"currentColor"}
						opacity={"0.2"}
					/>
					<path
						d={
							"M 8 0 C 12.418 0 15.999 3.582 16 8 C 16 8 16 9 15 9 C 14 9 14 8 14 8 C 14 4.687 11.314 2 8 2 C 4.687 2 2 4.687 2 8 C 2 8 2 9 1 9 C 0 9 0 8 0 8 C 0 3.582 3.582 0 8 0 Z"
						}
						fill={"currentColor"}
					/>
				</svg>
			</motion.div>
		</motion.div>
	);
};
addPropertyControls(Input, {
	service: {
		title: "Service",
		type: ControlType.Enum,
		options: ["loops", "formspark", "mailchimp", "getwaitlist"],
		optionTitles: ["Loops", "FormSpark", "MailChimp", "Get Waitlist"],
		defaultValue: "loops",
	},
	mailchimpURL: {
		title: "URL",
		placeholder: "https://***.us6.list-manage.com/subscribe/post?u=***",
		type: ControlType.String,
		hidden: (props) => props.service !== "mailchimp",
	},
	loopsID: {
		title: "ID",
		placeholder: "klm2jxy0i98abzr01pq7defg5",
		type: ControlType.String,
		hidden: (props) => props.service !== "loops",
	},
	loopsUserGroup: {
		title: "User Group",
		type: ControlType.String,
		placeholder: "Title",
		optional: true,
		hidden: (props) => props.service !== "loops",
	},
	formsparkID: {
		title: "ID",
		placeholder: "7PbPpGN3",
		type: ControlType.String,
		hidden: (props) => props.service !== "formspark",
	},
	getwaitlistAPI: {
		title: "ID",
		placeholder: "9148",
		type: ControlType.String,
		hidden: (props) => props.service !== "getwaitlist",
	},
	redirectAs: {
		title: "Success",
		type: ControlType.Enum,
		options: ["link", "overlay"],
		optionTitles: ["Open Link", "Show Overlay"],
		defaultValue: "link",
	},
	link: {
		title: "Redirect",
		type: ControlType.Link,
		hidden: (props) => props.redirectAs === "overlay",
	},
	onSubmit: {
		title: "Submit",
		type: ControlType.EventHandler,
		hidden: (props) => props.redirectAs === "link",
	},
	layout: {
		title: "Layout",
		type: ControlType.Enum,
		options: ["horizontal", "vertical"],
		displaySegmentedControl: true,
		hidden: (props) => props.button.isDocked,
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
	},
	input: {
		title: "Input",
		type: ControlType.Object,
		controls: {
			placeholder: {
				title: "Placeholder",
				type: ControlType.String,
				defaultValue: "name@email.com",
			},
			placeholderColor: {
				title: " ",
				type: ControlType.Color,
				defaultValue: "rgba(0, 0, 0, 0.3)",
			},
			fill: {
				title: "Fill",
				type: ControlType.Color,
				defaultValue: "#EBEBEB",
			},
			color: {
				title: "Text",
				type: ControlType.Color,
				defaultValue: "#000",
			},
			height: {
				title: "Height",
				type: ControlType.Boolean,
				enabledTitle: "Auto",
				disabledTitle: "Fixed",
			},
			fixedHeight: {
				title: " ",
				type: ControlType.Number,
				displayStepper: true,
				min: 0,
				defaultValue: 50,
				hidden: (props) => props.height,
			},
			padding: {
				title: "Padding",
				type: ControlType.FusedNumber,
				toggleKey: "paddingPerSide",
				toggleTitles: ["Padding", "Padding per side"],
				defaultValue: 15,
				valueKeys: [
					"paddingTop",
					"paddingRight",
					"paddingBottom",
					"paddingLeft",
				],
				valueLabels: ["T", "R", "B", "L"],
				min: 0,
			},
			borderRadius: {
				title: "Radius",
				type: ControlType.Number,
				displayStepper: true,
				min: 0,
				defaultValue: 8,
			},
			focusObject: {
				type: ControlType.Object,
				title: "Focus",
				optional: true,
				controls: {
					focusWidthFrom: {
						title: "From",
						type: ControlType.Number,
						displayStepper: true,
						defaultValue: 0,
					},
					focusWidthTo: {
						title: "To",
						type: ControlType.Number,
						displayStepper: true,
						defaultValue: 2,
					},
					focusColor: {
						title: "Color",
						type: ControlType.Color,
						defaultValue: "#09F",
					},
				},
			},
			borderObject: {
				type: ControlType.Object,
				title: "Border",
				optional: true,
				controls: {
					borderWidth: {
						title: "Width",
						type: ControlType.Number,
						displayStepper: true,
						defaultValue: 1,
					},
					borderColor: {
						title: "Color",
						type: ControlType.Color,
						defaultValue: "rgba(200,200,200,0.5)",
					},
				},
			},
			shadowObject: {
				type: ControlType.Object,
				title: "Shadow",
				optional: true,
				controls: {
					shadowColor: {
						title: "Color",
						type: ControlType.Color,
						defaultValue: "rgba(0,0,0,0.25)",
					},
					shadowX: {
						title: "Shadow X",
						type: ControlType.Number,
						min: -100,
						max: 100,
						defaultValue: 0,
					},
					shadowY: {
						title: "Shadow Y",
						type: ControlType.Number,
						min: -100,
						max: 100,
						defaultValue: 2,
					},
					shadowBlur: {
						title: "Shadow B",
						type: ControlType.Number,
						min: 0,
						max: 100,
						defaultValue: 4,
					},
				},
			},
		},
	},
	button: {
		title: "Button",
		type: ControlType.Object,
		controls: {
			shouldAppear: {
				title: "Show",
				type: ControlType.Boolean,
				defaultValue: true,
			},
			label: {
				title: "Label",
				type: ControlType.String,
				defaultValue: "Subscribe",
			},
			buttonFont: {
				type: ControlType.Font,
				title: "Font",
				controls: "extended",
			},
			fill: {
				title: "Fill",
				type: ControlType.Color,
				defaultValue: "#333",
			},
			color: {
				title: "Text",
				type: ControlType.Color,
				defaultValue: "#FFF",
			},
			isDocked: {
				title: "Docked",
				type: ControlType.Boolean,
				defaultValue: false,
			},
			widthWhenDocked: {
				title: "Width",
				type: ControlType.Number,
				min: 0,
				defaultValue: 100,
				displayStepper: true,
				hidden: (props) => !props.isDocked,
			},
			insetWhenDocked: {
				title: "Inset",
				type: ControlType.Number,
				min: 0,
				defaultValue: 5,
				displayStepper: true,
				hidden: (props) => !props.isDocked,
			},
			buttonPadding: {
				title: "Padding",
				type: ControlType.FusedNumber,
				toggleKey: "buttonPaddingPerSide",
				toggleTitles: ["Padding", "Padding per side"],
				defaultValue: 15,
				valueKeys: [
					"buttonPaddingTop",
					"buttonPaddingRight",
					"buttonPaddingBottom",
					"buttonPaddingLeft",
				],
				valueLabels: ["T", "R", "B", "L"],
				min: 0,
			},
			buttonShadow: {
				type: ControlType.Object,
				title: "Shadow",
				optional: true,
				controls: {
					shadowColor: {
						title: "Color",
						type: ControlType.Color,
						defaultValue: "rgba(0,0,0,0.25)",
					},
					shadowX: {
						title: "Shadow X",
						type: ControlType.Number,
						min: -100,
						max: 100,
						defaultValue: 0,
					},
					shadowY: {
						title: "Shadow Y",
						type: ControlType.Number,
						min: -100,
						max: 100,
						defaultValue: 2,
					},
					shadowBlur: {
						title: "Shadow B",
						type: ControlType.Number,
						min: 0,
						max: 100,
						defaultValue: 4,
					},
				},
			},
		},
	},
	gap: {
		title: "Gap",
		type: ControlType.Number,
		displayStepper: true,
		min: 0,
		defaultValue: 10,
		hidden: (props) => props.button.isDocked,
	},
});
var defaultStyle = {
	WebkitAppearance: "none",
	appearance: "none",
	width: "100%",
	height: "auto",
	outline: "none",
	border: "none",
};
var containerStyles = {
	position: "relative",
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
function getButtonShadow(button) {
	if (button.buttonShadow) {
		return `${button.buttonShadow.shadowX}px ${button.buttonShadow.shadowY}px ${button.buttonShadow.shadowBlur}px ${button.buttonShadow.shadowColor}`;
	} else return "none";
}
function dynamicBoxShadow(...shadows) {
	const output = [];
	shadows.forEach((shadow) => shadow && output.push(shadow));
	return output.join(", ");
}
var stdin_default = Input;

// /:https://framerusercontent.com/modules/gh9Cz7c2SlQG7G32uE4e/n2FGgF1vQpEWpe2cFHqV/IIGMd7Ixk.js
var InputFonts = getFonts(stdin_default);
var cycleOrder = ["XuvksIHfE", "QEzxJthPj", "zoIA1A44M"];
var serializationHash = "framer-PGi3r";
var variantClassNames = {
	QEzxJthPj: "framer-v-1iwa7g0",
	XuvksIHfE: "framer-v-aq0kw4",
	zoIA1A44M: "framer-v-1qaq722",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "XuvksIHfE",
	Phone: "zoIA1A44M",
	Tablet: "QEzxJthPj",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "XuvksIHfE",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XuvksIHfE",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className4, className, className2, className3];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion2.footer
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-aq0kw4",
						className5,
						classNames,
					)}
					data-border={true}
					data-framer-name={"Desktop"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"XuvksIHfE"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						"--border-bottom-width": "0px",
						"--border-color": "rgba(0, 0, 0, 0.05)",
						"--border-left-width": "0px",
						"--border-right-width": "0px",
						"--border-style": "solid",
						"--border-top-width": "1px",
						backgroundColor:
							"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15))",
						...style,
					}}
					{...addPropertyOverrides(
						{
							QEzxJthPj: {
								"data-framer-name": "Tablet",
							},
							zoIA1A44M: {
								"data-framer-name": "Phone",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion2.div
						className={"framer-sg3j6q"}
						data-framer-name={"Horizontal"}
						layoutDependency={layoutDependency}
						layoutId={"UaMVHPm1g"}
					>
						<motion2.div
							className={"framer-1639vre"}
							layoutDependency={layoutDependency}
							layoutId={"LMuWb2dTg"}
						>
							<motion2.div
								className={"framer-5tgkew"}
								data-framer-name={"Vertical"}
								layoutDependency={layoutDependency}
								layoutId={"axncEP6_I"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-nq13sh"}
									layoutDependency={layoutDependency}
									layoutId={"qzICQcfW7"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-1d3q4ow"}
											data-styles-preset={"B4kObtz8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250)))",
											}}
										>
											<Link
												href={{
													webPageId: "augiA20Il",
												}}
												openInNewTab={false}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Home"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-t70n1c"}
									layoutDependency={layoutDependency}
									layoutId={"DH6PzYdT9"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-1d3q4ow"}
											data-styles-preset={"B4kObtz8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250)))",
											}}
										>
											<Link
												href={{
													webPageId: "HatdPmJGV",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"About"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-mfquok"}
									layoutDependency={layoutDependency}
									layoutId={"R6RTz0lP8"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-1d3q4ow"}
											data-styles-preset={"B4kObtz8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250)))",
											}}
										>
											<Link
												href={{
													webPageId: "iM3JKMDKD",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"case studies"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-km1roi"}
									layoutDependency={layoutDependency}
									layoutId={"S6gxj6cVk"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-1d3q4ow"}
											data-styles-preset={"B4kObtz8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250)))",
											}}
										>
											<Link
												href={{
													webPageId: "udZZBGQWw",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"contact"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React.Fragment>
								</RichText>
							</motion2.div>
							<motion2.div
								className={"framer-3ctnl"}
								data-framer-name={"Vertical"}
								layoutDependency={layoutDependency}
								layoutId={"WVB1SnzLH"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1w7s6bk"}
									layoutDependency={layoutDependency}
									layoutId={"z4uLjIYr_"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250))",
										"--framer-link-hover-text-color":
											"rgba(153, 153, 153, 0.6)",
										"--framer-link-text-decoration": "none",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-1d3q4ow"}
											data-styles-preset={"B4kObtz8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250)))",
											}}
										>
											{"Scale With Us"}
										</motion2.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-tgt4x5"}
									layoutDependency={layoutDependency}
									layoutId={"o61kI2PSe"}
									style={{
										"--extracted-r6o4lv": "rgb(196, 196, 196)",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-15zjald"}
											data-styles-preset={"Ge7bltu5p"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(196, 196, 196))",
											}}
										>
											<Link
												href={"mailto:hello@unhinged.com"}
												openInNewTab={true}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"hello@unhinged.com"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-fig3gp"}
									layoutDependency={layoutDependency}
									layoutId={"VWtrCJJLi"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250))",
										"--framer-link-hover-text-color":
											"rgba(153, 153, 153, 0.6)",
										"--framer-link-text-decoration": "none",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-1d3q4ow"}
											data-styles-preset={"B4kObtz8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-ee4fa4fe-0cfe-433f-81df-73f19965f374, rgb(250, 250, 250)))",
											}}
										>
											{"Join Us"}
										</motion2.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ttx3js"}
									layoutDependency={layoutDependency}
									layoutId={"PmH2K4Jqh"}
									style={{
										"--extracted-r6o4lv": "rgb(196, 196, 196)",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion2.p
											className={"framer-styles-preset-15zjald"}
											data-styles-preset={"Ge7bltu5p"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(196, 196, 196))",
											}}
										>
											<Link
												href={"mailto:talent@uhinged.com"}
												openInNewTab={true}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"talent@unhinged.com"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React.Fragment>
								</RichText>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-15p4jae"}
							data-border={true}
							layoutDependency={layoutDependency}
							layoutId={"kVu0iPIp1"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 255, 255, 0.35)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15))",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
								boxShadow: "0px 10px 30px 0px rgba(142, 45, 166, 0.1)",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1d1uwwx"}
								layoutDependency={layoutDependency}
								layoutId={"LJVUfq_j3"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion2.h6
										className={"framer-styles-preset-njlb1o"}
										data-styles-preset={"HfKv2RvpD"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
										}}
									>
										{"Don't miss out on all our updates!"}
									</motion2.h6>
								</React.Fragment>
							</RichText>
							<motion2.div
								className={"framer-1rw2rvj"}
								layoutDependency={layoutDependency}
								layoutId={"IbTOB6lmF"}
							>
								<motion2.div
									className={"framer-16vokrc-container"}
									layoutDependency={layoutDependency}
									layoutId={"GvgYXwpNM-container"}
								>
									{_jsx2(stdin_default, {
										button: {
											buttonFont: {
												fontFamily:
													'"Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif',
												fontSize: "16px",
												fontStyle: "normal",
												fontWeight: 700,
												letterSpacing: "0em",
												lineHeight: "1em",
											},
											buttonPadding: 15,
											buttonPaddingBottom: 15,
											buttonPaddingLeft: 15,
											buttonPaddingPerSide: false,
											buttonPaddingRight: 15,
											buttonPaddingTop: 15,
											color: "rgb(255, 255, 255)",
											fill: 'var(--token-232ed45b-8622-40fa-9eba-51c55023a20d, rgb(140, 44, 165)) /* {"name":"Violet"} */',
											insetWhenDocked: 5,
											isDocked: false,
											label: "SUBSCRIBE",
											shouldAppear: true,
											widthWhenDocked: 150,
										},
										font: {},
										formsparkID: "",
										gap: 8,
										getwaitlistAPI: "",
										height: "100%",
										id: "GvgYXwpNM",
										input: {
											borderRadius: 36,
											color: "rgb(0, 0, 0)",
											fill: "rgb(235, 235, 235)",
											fixedHeight: 50,
											height: true,
											padding: 15,
											paddingBottom: 15,
											paddingLeft: 15,
											paddingPerSide: false,
											paddingRight: 15,
											paddingTop: 15,
											placeholder: "name@email.com",
											placeholderColor: "rgba(0, 0, 0, 0.3)",
										},
										layout: "horizontal",
										layoutId: "GvgYXwpNM",
										loopsID: "",
										loopsUserGroup: "",
										mailchimpURL: "",
										redirectAs: "overlay",
										service: "loops",
										style: {
											width: "100%",
										},
										width: "100%",
										...addPropertyOverrides(
											{
												zoIA1A44M: {
													layout: "vertical",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</motion2.div>
					<motion2.div
						className={"framer-1tgt4eq"}
						data-border={true}
						data-framer-name={"Copyright"}
						layoutDependency={layoutDependency}
						layoutId={"uV6L1Kroa"}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(255, 255, 255, 0.2)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "1px",
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-xse3i2"}
							layoutDependency={layoutDependency}
							layoutId={"pjpD6Yzf3"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
								"--framer-link-hover-text-color": "rgba(153, 153, 153, 0.6)",
								"--framer-link-text-decoration": "none",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion2.p
									className={"framer-styles-preset-1d3q4ow"}
									data-styles-preset={"B4kObtz8Z"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
									}}
								>
									{"\xA9 2023 UNHINGED. ALL RIGHTS RESERVED."}
								</motion2.p>
							</React.Fragment>
						</RichText>
					</motion2.div>
				</motion2.footer>
			</Transition>
		</LayoutGroup>
	);
});
var css5 = [
	'.framer-PGi3r[data-border="true"]::after, .framer-PGi3r [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PGi3r.framer-8knn7f, .framer-PGi3r .framer-8knn7f { display: block; }",
	".framer-PGi3r.framer-aq0kw4 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px 120px 40px 120px; position: relative; width: 1200px; }",
	".framer-PGi3r .framer-sg3j6q { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-PGi3r .framer-1639vre { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-PGi3r .framer-5tgkew, .framer-PGi3r .framer-3ctnl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-PGi3r .framer-nq13sh, .framer-PGi3r .framer-t70n1c, .framer-PGi3r .framer-mfquok, .framer-PGi3r .framer-km1roi, .framer-PGi3r .framer-1w7s6bk, .framer-PGi3r .framer-tgt4x5, .framer-PGi3r .framer-fig3gp, .framer-PGi3r .framer-ttx3js, .framer-PGi3r .framer-xse3i2 { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }",
	".framer-PGi3r .framer-15p4jae { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 40px 40px 40px 40px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-PGi3r .framer-1d1uwwx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-PGi3r .framer-1rw2rvj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-PGi3r .framer-16vokrc-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-PGi3r .framer-1tgt4eq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 30px 0px 0px 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PGi3r.framer-aq0kw4, .framer-PGi3r .framer-sg3j6q, .framer-PGi3r .framer-1639vre, .framer-PGi3r .framer-5tgkew, .framer-PGi3r .framer-3ctnl, .framer-PGi3r .framer-15p4jae, .framer-PGi3r .framer-1rw2rvj { gap: 0px; } .framer-PGi3r.framer-aq0kw4 > * { margin: 0px; margin-bottom: calc(64px / 2); margin-top: calc(64px / 2); } .framer-PGi3r.framer-aq0kw4 > :first-child, .framer-PGi3r .framer-5tgkew > :first-child, .framer-PGi3r .framer-3ctnl > :first-child, .framer-PGi3r .framer-15p4jae > :first-child { margin-top: 0px; } .framer-PGi3r.framer-aq0kw4 > :last-child, .framer-PGi3r .framer-5tgkew > :last-child, .framer-PGi3r .framer-3ctnl > :last-child, .framer-PGi3r .framer-15p4jae > :last-child { margin-bottom: 0px; } .framer-PGi3r .framer-sg3j6q > *, .framer-PGi3r .framer-1639vre > * { margin: 0px; margin-left: calc(60px / 2); margin-right: calc(60px / 2); } .framer-PGi3r .framer-sg3j6q > :first-child, .framer-PGi3r .framer-1639vre > :first-child, .framer-PGi3r .framer-1rw2rvj > :first-child { margin-left: 0px; } .framer-PGi3r .framer-sg3j6q > :last-child, .framer-PGi3r .framer-1639vre > :last-child, .framer-PGi3r .framer-1rw2rvj > :last-child { margin-right: 0px; } .framer-PGi3r .framer-5tgkew > *, .framer-PGi3r .framer-3ctnl > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-PGi3r .framer-15p4jae > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-PGi3r .framer-1rw2rvj > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } }",
	".framer-PGi3r.framer-v-1iwa7g0.framer-aq0kw4 { padding: 40px 80px 40px 80px; width: 810px; }",
	".framer-PGi3r.framer-v-1iwa7g0 .framer-sg3j6q, .framer-PGi3r.framer-v-1qaq722 .framer-sg3j6q { flex-direction: column; gap: 40px; }",
	".framer-PGi3r.framer-v-1iwa7g0 .framer-1639vre { order: 1; width: 100%; }",
	".framer-PGi3r.framer-v-1iwa7g0 .framer-5tgkew, .framer-PGi3r.framer-v-1iwa7g0 .framer-3ctnl { flex: 1 0 0px; height: auto; width: 1px; }",
	".framer-PGi3r.framer-v-1iwa7g0 .framer-15p4jae { flex: none; height: auto; order: 0; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PGi3r.framer-v-1iwa7g0 .framer-sg3j6q { gap: 0px; } .framer-PGi3r.framer-v-1iwa7g0 .framer-sg3j6q > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-PGi3r.framer-v-1iwa7g0 .framer-sg3j6q > :first-child { margin-top: 0px; } .framer-PGi3r.framer-v-1iwa7g0 .framer-sg3j6q > :last-child { margin-bottom: 0px; } }",
	".framer-PGi3r.framer-v-1qaq722.framer-aq0kw4 { padding: 40px 20px 56px 20px; width: 390px; }",
	".framer-PGi3r.framer-v-1qaq722 .framer-1639vre { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 40px; order: 1; }",
	".framer-PGi3r.framer-v-1qaq722 .framer-15p4jae { flex: none; order: 0; width: 100%; }",
	".framer-PGi3r.framer-v-1qaq722 .framer-1d1uwwx { white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-PGi3r.framer-v-1qaq722 .framer-1rw2rvj { flex-direction: column; }",
	".framer-PGi3r.framer-v-1qaq722 .framer-16vokrc-container { flex: none; width: 100%; }",
	".framer-PGi3r.framer-v-1qaq722 .framer-xse3i2 { overflow: hidden; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PGi3r.framer-v-1qaq722 .framer-sg3j6q, .framer-PGi3r.framer-v-1qaq722 .framer-1639vre, .framer-PGi3r.framer-v-1qaq722 .framer-1rw2rvj { gap: 0px; } .framer-PGi3r.framer-v-1qaq722 .framer-sg3j6q > *, .framer-PGi3r.framer-v-1qaq722 .framer-1639vre > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-PGi3r.framer-v-1qaq722 .framer-sg3j6q > :first-child, .framer-PGi3r.framer-v-1qaq722 .framer-1639vre > :first-child, .framer-PGi3r.framer-v-1qaq722 .framer-1rw2rvj > :first-child { margin-top: 0px; } .framer-PGi3r.framer-v-1qaq722 .framer-sg3j6q > :last-child, .framer-PGi3r.framer-v-1qaq722 .framer-1639vre > :last-child, .framer-PGi3r.framer-v-1qaq722 .framer-1rw2rvj > :last-child { margin-bottom: 0px; } .framer-PGi3r.framer-v-1qaq722 .framer-1rw2rvj > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	...css4,
	...css,
	...css2,
	...css3,
];
var FramerIIGMd7Ixk = withCSS2(Component, css5, "framer-PGi3r");
var stdin_default2 = FramerIIGMd7Ixk;
FramerIIGMd7Ixk.displayName = "Footer Dark";
FramerIIGMd7Ixk.defaultProps = {
	height: 379,
	width: 1200,
};
addPropertyControls2(FramerIIGMd7Ixk, {
	variant: {
		options: ["XuvksIHfE", "QEzxJthPj", "zoIA1A44M"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(FramerIIGMd7Ixk, [
	{
		family: "Schibsted Grotesk",
		source: "google",
		style: "normal",
		url: "https://fonts.gstatic.com/s/schibstedgrotesk/v3/JqzK5SSPQuCQF3t8uOwiUL-taUTtarVKQ9vZ6pJJWlMNxcYASsJuXFGVOQ.woff2",
		weight: "700",
	},
	...InputFonts,
	...fonts4,
	...fonts,
	...fonts2,
	...fonts3,
]);

// virtual:footer-dark
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "zoIA1A44M",
	md: "QEzxJthPj",
	xl: "XuvksIHfE",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterDarkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_dark_default = ComponentWithRoot;
export { footer_dark_default as default };
