// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 762710f0f0c99651 "UNHINGED (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Ticker } from "./chunks/chunk-4EM4INMI.js";
import { className, css, fonts } from "./chunks/chunk-G2TO6BN5.js";
import { routes } from "./chunks/chunk-VGZ5GRAF.js";

// virtual:industries
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/g2CPTHCoNFeERIHgUzXH/RRqCvellxfFHdsvZPQNk/Pa8SSfFjL.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFonts,
	RichText,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var TickerFonts = getFonts(Ticker);
var cycleOrder = ["CQlR6V7DW"];
var serializationHash = "framer-qcnFi";
var variantClassNames = {
	CQlR6V7DW: "framer-v-yhlt27",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CQlR6V7DW",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-yhlt27",
						className2,
						classNames,
					)}
					data-framer-name={"Variant 1"}
					initial={variant}
					layoutDependency={layoutDependency}
					layoutId={"CQlR6V7DW"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
				>
					<motion.div
						className={"framer-377jpu-container"}
						data-framer-name={"Logos"}
						layoutDependency={layoutDependency}
						layoutId={"vIjBQArkN-container"}
						name={"Logos"}
					>
						<Ticker
							alignment={"center"}
							direction={"left"}
							fadeOptions={{
								fadeAlpha: 0,
								fadeContent: true,
								fadeInset: 0,
								fadeWidth: 25,
								overflow: false,
							}}
							gap={16}
							height={"100%"}
							hoverFactor={1}
							id={"vIjBQArkN"}
							layoutId={"vIjBQArkN"}
							name={"Logos"}
							padding={0}
							paddingBottom={0}
							paddingLeft={0}
							paddingPerSide={false}
							paddingRight={0}
							paddingTop={0}
							sizingOptions={{
								heightType: true,
								widthType: true,
							}}
							slots={[
								<motion.div
									className={"framer-1051hf3"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"i8gSDsdZm"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1o72q43"}
										layoutDependency={layoutDependency}
										layoutId={"mTbljGDzT"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"SaaS"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-v938rc"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"Iua7gKkIO"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-5mjgf"}
										layoutDependency={layoutDependency}
										layoutId={"zRPnSxnes"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Tech Startups"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-1pz59d4"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"AzYRBl8nR"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-rc6vgu"}
										layoutDependency={layoutDependency}
										layoutId={"UXYiclHqZ"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"FinTech"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-13kz9bz"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"xhT04XoH0"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1arndew"}
										layoutDependency={layoutDependency}
										layoutId={"U54hwnWv_"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Web3"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-n8xgyg"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"vBtCk3PCK"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-god2rr"}
										layoutDependency={layoutDependency}
										layoutId={"OxgZi6x7m"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Health & Wellness"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-28mr5v"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"Y1Oitb35m"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-12tqg5p"}
										layoutDependency={layoutDependency}
										layoutId={"aDehiQ_PV"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Agencies"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-1i0yibf"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"yr9Q_PYkB"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1ozqy2f"}
										layoutDependency={layoutDependency}
										layoutId={"yTsL92K6t"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Luxury Brands"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-1xp3xib"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"ATdb2DKLO"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-16f3wq2"}
										layoutDependency={layoutDependency}
										layoutId={"WkrXQTZTf"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Beauty Brands"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-15ig5ff"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"kxS67bp2Q"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-b3r3o4"}
										layoutDependency={layoutDependency}
										layoutId={"FuIq5iJeV"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Hotel & Resorts"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
								<motion.div
									className={"framer-okoq1m"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"QbkzL1j60"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-1081f20a-c839-4972-8e7c-96d32d836610, rgb(177, 159, 181))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-5dc20c5d-c535-4583-a5f4-b96da9e232ae, rgb(62, 40, 66))",
										borderBottomLeftRadius: 42,
										borderBottomRightRadius: 42,
										borderTopLeftRadius: 42,
										borderTopRightRadius: 42,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1taykww"}
										layoutDependency={layoutDependency}
										layoutId={"N_aaaYj8x"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-15zjald"}
												data-styles-preset={"Ge7bltu5p"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
												}}
											>
												{"Travel Agency"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>,
							]}
							speed={70}
							style={{
								height: "100%",
								width: "100%",
							}}
							width={"100%"}
						/>
					</motion.div>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-qcnFi[data-border="true"]::after, .framer-qcnFi [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qcnFi.framer-ntngxd, .framer-qcnFi .framer-ntngxd { display: block; }",
	".framer-qcnFi.framer-yhlt27 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 50px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-qcnFi .framer-377jpu-container { flex: none; height: 105px; position: relative; width: 1120px; }",
	".framer-qcnFi .framer-1051hf3, .framer-qcnFi .framer-v938rc, .framer-qcnFi .framer-1pz59d4, .framer-qcnFi .framer-13kz9bz, .framer-qcnFi .framer-n8xgyg, .framer-qcnFi .framer-28mr5v, .framer-qcnFi .framer-1i0yibf, .framer-qcnFi .framer-1xp3xib, .framer-qcnFi .framer-15ig5ff, .framer-qcnFi .framer-okoq1m { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 20px 10px 20px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-qcnFi .framer-1o72q43, .framer-qcnFi .framer-5mjgf, .framer-qcnFi .framer-rc6vgu, .framer-qcnFi .framer-1arndew, .framer-qcnFi .framer-god2rr, .framer-qcnFi .framer-12tqg5p, .framer-qcnFi .framer-1ozqy2f, .framer-qcnFi .framer-16f3wq2, .framer-qcnFi .framer-b3r3o4, .framer-qcnFi .framer-1taykww { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-qcnFi.framer-yhlt27, .framer-qcnFi .framer-1051hf3, .framer-qcnFi .framer-v938rc, .framer-qcnFi .framer-1pz59d4, .framer-qcnFi .framer-13kz9bz, .framer-qcnFi .framer-n8xgyg, .framer-qcnFi .framer-28mr5v, .framer-qcnFi .framer-1i0yibf, .framer-qcnFi .framer-1xp3xib, .framer-qcnFi .framer-15ig5ff, .framer-qcnFi .framer-okoq1m { gap: 0px; } .framer-qcnFi.framer-yhlt27 > *, .framer-qcnFi .framer-1051hf3 > *, .framer-qcnFi .framer-v938rc > *, .framer-qcnFi .framer-1pz59d4 > *, .framer-qcnFi .framer-13kz9bz > *, .framer-qcnFi .framer-n8xgyg > *, .framer-qcnFi .framer-28mr5v > *, .framer-qcnFi .framer-1i0yibf > *, .framer-qcnFi .framer-1xp3xib > *, .framer-qcnFi .framer-15ig5ff > *, .framer-qcnFi .framer-okoq1m > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-qcnFi.framer-yhlt27 > :first-child, .framer-qcnFi .framer-1051hf3 > :first-child, .framer-qcnFi .framer-v938rc > :first-child, .framer-qcnFi .framer-1pz59d4 > :first-child, .framer-qcnFi .framer-13kz9bz > :first-child, .framer-qcnFi .framer-n8xgyg > :first-child, .framer-qcnFi .framer-28mr5v > :first-child, .framer-qcnFi .framer-1i0yibf > :first-child, .framer-qcnFi .framer-1xp3xib > :first-child, .framer-qcnFi .framer-15ig5ff > :first-child, .framer-qcnFi .framer-okoq1m > :first-child { margin-left: 0px; } .framer-qcnFi.framer-yhlt27 > :last-child, .framer-qcnFi .framer-1051hf3 > :last-child, .framer-qcnFi .framer-v938rc > :last-child, .framer-qcnFi .framer-1pz59d4 > :last-child, .framer-qcnFi .framer-13kz9bz > :last-child, .framer-qcnFi .framer-n8xgyg > :last-child, .framer-qcnFi .framer-28mr5v > :last-child, .framer-qcnFi .framer-1i0yibf > :last-child, .framer-qcnFi .framer-1xp3xib > :last-child, .framer-qcnFi .framer-15ig5ff > :last-child, .framer-qcnFi .framer-okoq1m > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerPa8SSfFjL = withCSS(Component, css2, "framer-qcnFi");
var stdin_default = FramerPa8SSfFjL;
FramerPa8SSfFjL.displayName = "Industries";
FramerPa8SSfFjL.defaultProps = {
	height: 50,
	width: 1120,
};
addFonts(FramerPa8SSfFjL, [...TickerFonts, ...fonts]);

// virtual:industries
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IndustriesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var industries_default = ComponentWithRoot;
export { industries_default as default };
