// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 762710f0f0c99651 "UNHINGED (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-CCFKFPA2.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-G2TO6BN5.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-W6FT4636.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-FAVGGUSS.js";
import { routes } from "./chunks/chunk-VGZ5GRAF.js";

// virtual:navbar
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gWeEPH905t6yvMmLFQV0/AYSB5mhfrOog94BMfe5g/DSpwbEWNS.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	Link as Link2,
	RichText as RichText2,
	SVG as SVG2,
	useActiveVariantCallback,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/tf8czCCv9fmaFp6AwpWc/yPz6dGA7u8trSeo5ddTr/cL3cEjAj4.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Inter-700",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts5 = [
	{
		family: "Inter",
		source: "google",
		style: "normal",
		url: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZ1rib2Bg-4.woff2",
		weight: "700",
	},
];
var css5 = [
	'.framer-V7qhZ .framer-styles-preset-1241yam:not(.rich-text-wrapper), .framer-V7qhZ .framer-styles-preset-1241yam.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter-Bold", "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter-BoldItalic", "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter-Italic", "Inter", "Inter Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className5 = "framer-V7qhZ";

// /:https://framerusercontent.com/modules/kLkkyMmMvzG0YOqpqYId/urSfYykg6fbo3dEoPsRC/fkjc8Ci1l.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Schibsted Grotesk-600",
	"GF;Schibsted Grotesk-900",
	"GF;Schibsted Grotesk-900italic",
	"GF;Schibsted Grotesk-600italic",
]);
var fonts6 = [
	{
		family: "Schibsted Grotesk",
		style: "normal",
		url: "https://fonts.gstatic.com/s/schibstedgrotesk/v3/JqzK5SSPQuCQF3t8uOwiUL-taUTtarVKQ9vZ6pJJWlMN_MYASsJuXFGVOQ.woff2",
		weight: "600",
	},
	{
		family: "Schibsted Grotesk",
		style: "normal",
		url: "https://fonts.gstatic.com/s/schibstedgrotesk/v3/JqzK5SSPQuCQF3t8uOwiUL-taUTtarVKQ9vZ6pJJWlMNi8YASsJuXFGVOQ.woff2",
		weight: "900",
	},
	{
		family: "Schibsted Grotesk",
		style: "italic",
		url: "https://fonts.gstatic.com/s/schibstedgrotesk/v3/JqzI5SSPQuCQF3t8uOwiUL-taUTtap9DcSQBg_nT9FQY6oJBC8hvflSFOTXs.woff2",
		weight: "900",
	},
	{
		family: "Schibsted Grotesk",
		style: "italic",
		url: "https://fonts.gstatic.com/s/schibstedgrotesk/v3/JqzI5SSPQuCQF3t8uOwiUL-taUTtap9DcSQBg_nT9FQY6oI2C8hvflSFOTXs.woff2",
		weight: "600",
	},
];
var css6 = [
	'.framer-RE7ze .framer-styles-preset-g6rza9:not(.rich-text-wrapper), .framer-RE7ze .framer-styles-preset-g6rza9.rich-text-wrapper h2 { --framer-font-family: "Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif; --framer-font-family-bold: "Schibsted Grotesk", sans-serif; --framer-font-family-bold-italic: "Schibsted Grotesk", sans-serif; --framer-font-family-italic: "Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #050505; --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-RE7ze .framer-styles-preset-g6rza9:not(.rich-text-wrapper), .framer-RE7ze .framer-styles-preset-g6rza9.rich-text-wrapper h2 { --framer-font-family: "Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif; --framer-font-family-bold: "Schibsted Grotesk", sans-serif; --framer-font-family-bold-italic: "Schibsted Grotesk", sans-serif; --framer-font-family-italic: "Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #050505; --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-RE7ze .framer-styles-preset-g6rza9:not(.rich-text-wrapper), .framer-RE7ze .framer-styles-preset-g6rza9.rich-text-wrapper h2 { --framer-font-family: "Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif; --framer-font-family-bold: "Schibsted Grotesk", sans-serif; --framer-font-family-bold-italic: "Schibsted Grotesk", sans-serif; --framer-font-family-italic: "Schibsted Grotesk", "Schibsted Grotesk Placeholder", sans-serif; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #050505; --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className6 = "framer-RE7ze";

// /:https://framerusercontent.com/modules/CLpRNrOhx83V9lvleUbm/VquVClbGIYEBCZxcDu9a/VCAWuBjXA.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([]);
var fonts7 = [];
var css7 = [
	".framer-vwDOC .framer-styles-preset-1oep8b8:not(.rich-text-wrapper), .framer-vwDOC .framer-styles-preset-1oep8b8.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-decoration: none; --framer-link-text-decoration: none; }",
];
var className7 = "framer-vwDOC";

// /:https://framerusercontent.com/modules/sZiCp7UKkqDmpY2mKB7j/yaois931Qjv2KTiAkT5H/jBGIqn2mr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	dl5AfPGN9: {
		hover: true,
	},
	gF_65Ml1c: {
		hover: true,
	},
	uGFcAoBjt: {
		hover: true,
	},
};
var cycleOrder = ["dl5AfPGN9", "gF_65Ml1c", "uGFcAoBjt"];
var serializationHash = "framer-JhJBk";
var variantClassNames = {
	dl5AfPGN9: "framer-v-1e8jjh0",
	gF_65Ml1c: "framer-v-vvpttt",
	uGFcAoBjt: "framer-v-1e9a1bt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "dl5AfPGN9",
	"Variant 2": "gF_65Ml1c",
	Mobile: "uGFcAoBjt",
};
var getProps = ({ cTA, height, id, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		qf8EYhhDy:
			(_ref = cTA !== null && cTA !== void 0 ? cTA : props.qf8EYhhDy) !==
				null && _ref !== void 0
				? _ref
				: "Get template",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "dl5AfPGN9",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		qf8EYhhDy,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "dl5AfPGN9",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["gF_65Ml1c-hover", "uGFcAoBjt-hover"].includes(gestureVariant))
			return false;
		if (["gF_65Ml1c", "uGFcAoBjt"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className4];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition}>
					<Link
						href={
							"https://viflordesign.lemonsqueezy.com/checkout/buy/a8209f56-5fb7-44f9-9910-69ec5ca17861"
						}
						openInNewTab={true}
					>
						<motion.a
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-1e8jjh0", className8, classNames)} framer-i7g904`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"dl5AfPGN9"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								background:
									"linear-gradient(180deg, rgb(222, 70, 242) 0%, #8C2CA5 100%)",
								borderBottomLeftRadius: 37,
								borderBottomRightRadius: 37,
								borderTopLeftRadius: 37,
								borderTopRightRadius: 37,
								...style,
							}}
							variants={{
								"dl5AfPGN9-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										'var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {"name":"90 Black"} */',
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									background:
										'linear-gradient(180deg, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 0%, rgb(255, 255, 255) 100%)',
								},
								"gF_65Ml1c-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										'var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {"name":"90 Black"} */',
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									background:
										'linear-gradient(180deg, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 0%, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 100%)',
								},
								"uGFcAoBjt-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										'var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {"name":"90 Black"} */',
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									background:
										'linear-gradient(180deg, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 0%, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) /* {"name":"100 White"} */ 100%)',
								},
								gF_65Ml1c: {
									background:
										"linear-gradient(180deg, rgb(222, 70, 242) 0%, rgb(140, 44, 165) 100%)",
								},
								uGFcAoBjt: {
									background:
										"linear-gradient(180deg, rgb(222, 70, 242) 0%, rgb(140, 44, 165) 100%)",
								},
							}}
							{...addPropertyOverrides(
								{
									"dl5AfPGN9-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									"gF_65Ml1c-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									"uGFcAoBjt-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									gF_65Ml1c: {
										"data-framer-name": "Variant 2",
									},
									uGFcAoBjt: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-10iugvl"}
								layoutDependency={layoutDependency}
								layoutId={"vde_q4kmo"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={qf8EYhhDy}
								variants={{
									"dl5AfPGN9-hover": {
										"--extracted-r6o4lv":
											"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) ",
									},
									"gF_65Ml1c-hover": {
										"--extracted-r6o4lv":
											"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) ",
									},
									"uGFcAoBjt-hover": {
										"--extracted-r6o4lv":
											"var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) ",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"dl5AfPGN9-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wuumuu"}
														data-styles-preset={"kRKaKn3c7"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) )",
														}}
													>
														{"Get template"}
													</motion.p>
												</React.Fragment>
											),
										},
										"gF_65Ml1c-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wuumuu"}
														data-styles-preset={"kRKaKn3c7"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) )",
														}}
													>
														{"Get template"}
													</motion.p>
												</React.Fragment>
											),
										},
										"uGFcAoBjt-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wuumuu"}
														data-styles-preset={"kRKaKn3c7"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) )",
														}}
													>
														{"Get template"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1wuumuu"}
										data-styles-preset={"kRKaKn3c7"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
										}}
									>
										{"Boost your brand"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<SVG
									className={"framer-1fsy85x"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"e0GbT2vHR-shape"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 53 53"><path d="M 0 35.074 L 35.192 0 L 35.192 12 L 35.192 0 L 23.192 0" transform="translate(9.247 9.005) rotate(45 17.596 17.537)" fill="transparent" stroke-width="1.5" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round" stroke-linejoin="round"></path></svg>'
									}
									svgContentId={2508863456}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"dl5AfPGN9-hover": {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 53 53"><path d="M 0 35.074 L 35.192 0 L 35.192 12 L 35.192 0 L 23.192 0" transform="translate(9.247 9.005) rotate(45 17.596 17.537)" fill="transparent" stroke-width="1.5" stroke="var(--token-9e113a59-f58c-49a9-941d-7d67abf873b3, rgb(13, 4, 15)) /* {&quot;name&quot;:&quot;90 Black&quot;} */" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
												svgContentId: 1405563195,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css8 = [
	'.framer-JhJBk[data-border="true"]::after, .framer-JhJBk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JhJBk.framer-i7g904, .framer-JhJBk .framer-i7g904 { display: block; }",
	".framer-JhJBk.framer-1e8jjh0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 40px; justify-content: center; overflow: visible; padding: 16px 32px 16px 32px; position: relative; text-decoration: none; width: auto; }",
	".framer-JhJBk .framer-10iugvl { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-JhJBk .framer-1fsy85x { flex: none; height: 53px; position: relative; width: 53px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-JhJBk.framer-1e8jjh0 { gap: 0px; } .framer-JhJBk.framer-1e8jjh0 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-JhJBk.framer-1e8jjh0 > :first-child { margin-left: 0px; } .framer-JhJBk.framer-1e8jjh0 > :last-child { margin-right: 0px; } }",
	".framer-JhJBk.framer-v-1e9a1bt.framer-1e8jjh0 { height: 30px; padding: 16px 16px 16px 16px; }",
	...css4,
];
var FramerjBGIqn2mr = withCSS(Component, css8, "framer-JhJBk");
var stdin_default = FramerjBGIqn2mr;
FramerjBGIqn2mr.displayName = "Button";
FramerjBGIqn2mr.defaultProps = {
	height: 40,
	width: 248,
};
addPropertyControls(FramerjBGIqn2mr, {
	variant: {
		options: ["dl5AfPGN9", "gF_65Ml1c", "uGFcAoBjt"],
		optionTitles: ["Variant 1", "Variant 2", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	qf8EYhhDy: {
		defaultValue: "Get template",
		displayTextArea: false,
		title: "CTA",
		type: ControlType.String,
	},
});
addFonts(FramerjBGIqn2mr, [...fonts4]);

// /:https://framerusercontent.com/modules/gWeEPH905t6yvMmLFQV0/AYSB5mhfrOog94BMfe5g/DSpwbEWNS.js
var ButtonFonts = getFonts(stdin_default);
var cycleOrder2 = ["QUkhoH_ww", "Al_7HKzIe", "D646cZ6Dn", "rJk6XlsQ1"];
var serializationHash2 = "framer-PplER";
var variantClassNames2 = {
	Al_7HKzIe: "framer-v-1egxa4i",
	D646cZ6Dn: "framer-v-h2gcdr",
	QUkhoH_ww: "framer-v-cn3cw5",
	rJk6XlsQ1: "framer-v-cvk3ws",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions2 = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
	rJk6XlsQ1: {
		delay: 0,
		duration: 0.3,
		ease: [0.44, 0, 0.56, 1],
		type: "tween",
	},
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2(React2.Fragment);
var humanReadableVariantMap2 = {
	"Phone Open": "rJk6XlsQ1",
	Desktop: "QUkhoH_ww",
	Phone: "D646cZ6Dn",
	Tablet: "Al_7HKzIe",
};
var getProps2 = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "QUkhoH_ww",
	};
};
var createLayoutDependency2 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "QUkhoH_ww",
		transitions: transitions2,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapckufmz = activeVariantCallback(async (...args) => {
		setVariant("rJk6XlsQ1");
	});
	const onTap189c9c4 = activeVariantCallback(async (...args) => {
		setVariant("D646cZ6Dn");
	});
	const ref1 = React2.useRef(null);
	const isDisplayed = () => {
		if (["D646cZ6Dn", "rJk6XlsQ1"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["D646cZ6Dn", "rJk6XlsQ1"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "rJk6XlsQ1") return true;
		return false;
	};
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [
		className6,
		className7,
		className3,
		className2,
		className,
		className5,
	];
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition}>
					<motion2.div
						{...restProps}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-cn3cw5",
							className8,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"QUkhoH_ww"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								Al_7HKzIe: {
									"data-framer-name": "Tablet",
								},
								D646cZ6Dn: {
									"data-framer-name": "Phone",
								},
								rJk6XlsQ1: {
									"data-framer-name": "Phone Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-hnuxjx"}
							layoutDependency={layoutDependency}
							layoutId={"ot9UippoJ"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-d0rybz"}
								layoutDependency={layoutDependency}
								layoutId={"hlc613hPe"}
								style={{
									"--extracted-1of0zx5":
										"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
								}}
								variants={{
									Al_7HKzIe: {
										"--extracted-1w1cjl5":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									},
									D646cZ6Dn: {
										"--extracted-1w1cjl5":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									},
									rJk6XlsQ1: {
										"--extracted-1w1cjl5":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										Al_7HKzIe: {
											children: (
												<React2.Fragment>
													<motion2.h6
														className={"framer-styles-preset-njlb1o"}
														data-styles-preset={"HfKv2RvpD"}
														style={{
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
														}}
													>
														<Link2
															href={{
																webPageId: "augiA20Il",
															}}
															openInNewTab={false}
															smoothScroll={false}
														>
															<motion2.a
																className={"framer-styles-preset-1oep8b8"}
																data-styles-preset={"VCAWuBjXA"}
															>
																{"UNHINGED"}
															</motion2.a>
														</Link2>
													</motion2.h6>
												</React2.Fragment>
											),
										},
										D646cZ6Dn: {
											children: (
												<React2.Fragment>
													<motion2.h6
														className={"framer-styles-preset-njlb1o"}
														data-styles-preset={"HfKv2RvpD"}
														style={{
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
														}}
													>
														<Link2
															href={{
																webPageId: "augiA20Il",
															}}
															openInNewTab={false}
															smoothScroll={false}
														>
															<motion2.a
																className={"framer-styles-preset-1oep8b8"}
																data-styles-preset={"VCAWuBjXA"}
															>
																{"UNHINGED"}
															</motion2.a>
														</Link2>
													</motion2.h6>
												</React2.Fragment>
											),
										},
										rJk6XlsQ1: {
											children: (
												<React2.Fragment>
													<motion2.h6
														className={"framer-styles-preset-njlb1o"}
														data-styles-preset={"HfKv2RvpD"}
														style={{
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
														}}
													>
														<Link2
															href={{
																webPageId: "augiA20Il",
															}}
															openInNewTab={false}
															smoothScroll={false}
														>
															<motion2.a
																className={"framer-styles-preset-1oep8b8"}
																data-styles-preset={"VCAWuBjXA"}
															>
																{"UNHINGED"}
															</motion2.a>
														</Link2>
													</motion2.h6>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.h2
										className={"framer-styles-preset-g6rza9"}
										data-styles-preset={"fkjc8Ci1l"}
										style={{
											"--framer-text-color":
												"var(--extracted-1of0zx5, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
										}}
									>
										<Link2
											href={{
												webPageId: "augiA20Il",
											}}
											openInNewTab={false}
											smoothScroll={false}
										>
											<motion2.a
												className={"framer-styles-preset-1oep8b8"}
												data-styles-preset={"VCAWuBjXA"}
											>
												{"UNHINGED"}
											</motion2.a>
										</Link2>
									</motion2.h2>
								</React2.Fragment>
							</RichText2>
							{isDisplayed() && (
								<motion2.div
									className={"framer-1tom96z"}
									layoutDependency={layoutDependency}
									layoutId={"vSd1Mizbo"}
								>
									<motion2.div
										className={"framer-k1xps2"}
										layoutDependency={layoutDependency}
										layoutId={"pvP_cwQLU"}
										{...addPropertyOverrides2(
											{
												D646cZ6Dn: {
													"data-highlight": true,
													onTap: onTapckufmz,
												},
												rJk6XlsQ1: {
													"data-highlight": true,
													onTap: onTap189c9c4,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{isDisplayed() && (
											<SVG2
												className={"framer-1g8cpo7"}
												layout={"position"}
												layoutDependency={layoutDependency}
												layoutId={"jKIdxoSdK-shape"}
												opacity={1}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 14"><path d="M 23 1.304 L 0.75 1.304" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path><path d="M 23.25 7.464 L 1 7.464" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path><path d="M 23.25 12.357 L 1 12.357" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path></svg>'
												}
												svgContentId={2047997411}
												withExternalLayout={true}
												{...addPropertyOverrides2(
													{
														D646cZ6Dn: {
															svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 13"><path d="M 23 1.304 L 0.75 1.304" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path><path d="M 23.25 6.464 L 1 6.464" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path><path d="M 23.25 11.357 L 1 11.357" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path></svg>',
															svgContentId: 3016713097,
														},
														rJk6XlsQ1: {
															svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 22"><path d="M 22 21.5 L 2 1.5" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path><path d="M 22 1.5 L 2 21.5" fill="transparent" stroke="var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))" stroke-linecap="round"></path><path d="" fill="rgba(0,170,255,0.5)" stroke="#0AF"></path></svg>',
															svgContentId: 3651246264,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										)}
									</motion2.div>
									{isDisplayed() && (
										<motion2.div
											className={"framer-13w4yri-container"}
											layoutDependency={layoutDependency}
											layoutId={"n1_BmjGSK-container"}
										>
											{_jsx2(stdin_default, {
												height: "100%",
												id: "n1_BmjGSK",
												layoutId: "n1_BmjGSK",
												qf8EYhhDy: "Get template",
												style: {
													height: "100%",
												},
												variant: "uGFcAoBjt",
												width: "100%",
											})}
										</motion2.div>
									)}
								</motion2.div>
							)}
						</motion2.div>
						{isDisplayed1() && (
							<motion2.div
								className={"framer-51b4vv"}
								data-framer-name={"Links"}
								layoutDependency={layoutDependency}
								layoutId={"sCM6JbQfu"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-11i5bvv"}
									layoutDependency={layoutDependency}
									layoutId={"lk2p9kgIT"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-15zjald"}
											data-styles-preset={"Ge7bltu5p"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
											}}
										>
											<Link2
												href={{
													webPageId: "HatdPmJGV",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"About"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-lobrqh"}
									layoutDependency={layoutDependency}
									layoutId={"DcJ57ef84"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) ",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-15zjald"}
											data-styles-preset={"Ge7bltu5p"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)) )",
											}}
										>
											<Link2
												href={{
													hash: ":GNd5vQm65",
													webPageId: "augiA20Il",
												}}
												openInNewTab={false}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Pricing"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-u3w413"}
									layoutDependency={layoutDependency}
									layoutId={"mdPSCZ0hu"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-15zjald"}
											data-styles-preset={"Ge7bltu5p"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
											}}
										>
											<Link2
												href={{
													webPageId: "iM3JKMDKD",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Case Studies"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1k95ge0"}
									layoutDependency={layoutDependency}
									layoutId={"XD8KN6vCf"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-15zjald"}
											data-styles-preset={"Ge7bltu5p"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-79f26658-5366-4586-bae6-dbb7e7a921a8, rgb(255, 255, 255)))",
											}}
										>
											<Link2
												href={{
													webPageId: "udZZBGQWw",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Contact"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
						)}
						{isDisplayed1() && (
							<motion2.div
								className={"framer-fqscvw-container"}
								layoutDependency={layoutDependency}
								layoutId={"AEEandhD4-container"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "AEEandhD4",
									layoutId: "AEEandhD4",
									qf8EYhhDy: "Get template",
									style: {
										height: "100%",
									},
									variant: "gF_65Ml1c",
									width: "100%",
									...addPropertyOverrides2(
										{
											Al_7HKzIe: {
												variant: "uGFcAoBjt",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion2.div>
						)}
						{isDisplayed2() && (
							<motion2.div
								className={"framer-1b8hg1j"}
								data-framer-name={"Links"}
								layoutDependency={layoutDependency}
								layoutId={"CH0VcgMsG"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-275khg"}
									layoutDependency={layoutDependency}
									layoutId={"cln6w2ZVk"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1241yam"}
											data-styles-preset={"cL3cEjAj4"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255)))",
											}}
										>
											<Link2
												href={{
													webPageId: "HatdPmJGV",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"About"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1x84yj0"}
									layoutDependency={layoutDependency}
									layoutId={"WCaCoZVUN"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1241yam"}
											data-styles-preset={"cL3cEjAj4"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255)))",
											}}
										>
											<Link2
												href={{
													hash: ":GNd5vQm65",
													webPageId: "augiA20Il",
												}}
												openInNewTab={false}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Pricing"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-ejg4ga"}
									layoutDependency={layoutDependency}
									layoutId={"cxfFHPncM"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1241yam"}
											data-styles-preset={"cL3cEjAj4"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255)))",
											}}
										>
											<Link2
												href={{
													webPageId: "iM3JKMDKD",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Case Studies"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1dsj1uw"}
									layoutDependency={layoutDependency}
									layoutId={"iYQGh3bjl"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1241yam"}
											data-styles-preset={"cL3cEjAj4"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-f01aad28-5d32-41bf-aa7c-b0201d2bdf2a, rgb(249, 227, 255)))",
											}}
										>
											<Link2
												href={{
													webPageId: "udZZBGQWw",
												}}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-1i0kijj"}
													data-styles-preset={"BYScPED6o"}
												>
													{"Contact"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css9 = [
	'.framer-PplER[data-border="true"]::after, .framer-PplER [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PplER.framer-33juna, .framer-PplER .framer-33juna { display: block; }",
	".framer-PplER.framer-cn3cw5 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 16px 120px 16px 120px; position: relative; width: 1200px; }",
	".framer-PplER .framer-hnuxjx, .framer-PplER .framer-1tom96z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-PplER .framer-d0rybz, .framer-PplER .framer-11i5bvv, .framer-PplER .framer-lobrqh, .framer-PplER .framer-u3w413, .framer-PplER .framer-1k95ge0, .framer-PplER .framer-275khg, .framer-PplER .framer-1x84yj0, .framer-PplER .framer-ejg4ga, .framer-PplER .framer-1dsj1uw { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-PplER .framer-k1xps2 { flex: none; height: 24px; overflow: visible; position: relative; width: 25px; }",
	".framer-PplER .framer-1g8cpo7 { flex: none; height: 14px; left: calc(52.00000000000002% - 24px / 2); position: absolute; top: calc(41.66666666666669% - 14px / 2); width: 24px; }",
	".framer-PplER .framer-13w4yri-container { flex: none; height: 30px; position: relative; width: auto; }",
	".framer-PplER .framer-51b4vv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-PplER .framer-fqscvw-container { flex: none; height: 40px; position: relative; width: auto; }",
	".framer-PplER .framer-1b8hg1j { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PplER .framer-hnuxjx, .framer-PplER .framer-1tom96z, .framer-PplER .framer-51b4vv, .framer-PplER .framer-1b8hg1j { gap: 0px; } .framer-PplER .framer-hnuxjx > *, .framer-PplER .framer-1tom96z > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-PplER .framer-hnuxjx > :first-child, .framer-PplER .framer-1tom96z > :first-child, .framer-PplER .framer-51b4vv > :first-child { margin-left: 0px; } .framer-PplER .framer-hnuxjx > :last-child, .framer-PplER .framer-1tom96z > :last-child, .framer-PplER .framer-51b4vv > :last-child { margin-right: 0px; } .framer-PplER .framer-51b4vv > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-PplER .framer-1b8hg1j > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-PplER .framer-1b8hg1j > :first-child { margin-top: 0px; } .framer-PplER .framer-1b8hg1j > :last-child { margin-bottom: 0px; } }",
	".framer-PplER.framer-v-1egxa4i.framer-cn3cw5 { padding: 16px 80px 16px 80px; width: 810px; }",
	".framer-PplER.framer-v-h2gcdr.framer-cn3cw5 { padding: 16px 20px 16px 20px; width: 390px; }",
	".framer-PplER.framer-v-h2gcdr .framer-hnuxjx { flex: 1 0 0px; gap: unset; height: 30px; justify-content: space-between; order: 2; width: 1px; }",
	".framer-PplER.framer-v-h2gcdr .framer-k1xps2, .framer-PplER.framer-v-cvk3ws .framer-k1xps2 { cursor: pointer; order: 1; width: 24px; }",
	".framer-PplER.framer-v-h2gcdr .framer-1g8cpo7 { height: 13px; left: calc(50.00000000000002% - 24px / 2); top: calc(50.00000000000002% - 13px / 2); }",
	".framer-PplER.framer-v-h2gcdr .framer-13w4yri-container, .framer-PplER.framer-v-cvk3ws .framer-13w4yri-container { order: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PplER.framer-v-h2gcdr .framer-hnuxjx { gap: 0px; } .framer-PplER.framer-v-h2gcdr .framer-hnuxjx > *, .framer-PplER.framer-v-h2gcdr .framer-hnuxjx > :first-child, .framer-PplER.framer-v-h2gcdr .framer-hnuxjx > :last-child { margin: 0px; } }",
	".framer-PplER.framer-v-cvk3ws.framer-cn3cw5 { flex-direction: column; gap: 24px; justify-content: flex-start; padding: 16px 20px 16px 20px; width: 390px; }",
	".framer-PplER.framer-v-cvk3ws .framer-hnuxjx { gap: unset; height: 30px; justify-content: space-between; order: 2; width: 100%; }",
	".framer-PplER.framer-v-cvk3ws .framer-1g8cpo7 { height: 22px; left: calc(50.00000000000002% - 24px / 2); top: calc(50.00000000000002% - 22px / 2); }",
	".framer-PplER.framer-v-cvk3ws .framer-1b8hg1j { flex: none; order: 4; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PplER.framer-v-cvk3ws.framer-cn3cw5, .framer-PplER.framer-v-cvk3ws .framer-hnuxjx { gap: 0px; } .framer-PplER.framer-v-cvk3ws.framer-cn3cw5 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-PplER.framer-v-cvk3ws.framer-cn3cw5 > :first-child { margin-top: 0px; } .framer-PplER.framer-v-cvk3ws.framer-cn3cw5 > :last-child { margin-bottom: 0px; } .framer-PplER.framer-v-cvk3ws .framer-hnuxjx > *, .framer-PplER.framer-v-cvk3ws .framer-hnuxjx > :first-child, .framer-PplER.framer-v-cvk3ws .framer-hnuxjx > :last-child { margin: 0px; } }",
	...css6,
	...css7,
	...css3,
	...css2,
	...css,
	...css5,
];
var FramerDSpwbEWNS = withCSS2(Component2, css9, "framer-PplER");
var stdin_default2 = FramerDSpwbEWNS;
FramerDSpwbEWNS.displayName = "Navbar";
FramerDSpwbEWNS.defaultProps = {
	height: 80,
	width: 1200,
};
addPropertyControls2(FramerDSpwbEWNS, {
	variant: {
		options: ["QUkhoH_ww", "Al_7HKzIe", "D646cZ6Dn", "rJk6XlsQ1"],
		optionTitles: ["Desktop", "Tablet", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(FramerDSpwbEWNS, [
	...ButtonFonts,
	...fonts6,
	...fonts7,
	...fonts3,
	...fonts2,
	...fonts,
	...fonts5,
]);

// virtual:navbar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "D646cZ6Dn",
	md: "Al_7HKzIe",
	xl: "QUkhoH_ww",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"762710f0f0c99651912648d89ff67404fa31b990d7117a4ad863da8b8ce0a1bd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var navbar_default = ComponentWithRoot;
export { navbar_default as default };
