#!/bin/bash

echo "🔵 Linking local folder to Vercel project..."
vercel link --confirm

ENVIRONMENTS=("development" "preview" "production")

VARS=(
  NEXT_PUBLIC_SITE_URL
  NEXT_PUBLIC_SUPABASE_URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY
  NEXT_PUBLIC_STT_WS_URL

  SUPABASE_SERVICE_ROLE_KEY
  OPENAI_API_KEY
  DEEPGRAM_API_KEY
  ELEVENLABS_API_KEY
  ELEVENLABS_VOICE_ID
  NEXT_PUBLIC_ELEVENLABS_API_KEY
  NEXT_PUBLIC_ELEVENLABS_VOICE_ID_FR
  NEXT_PUBLIC_ELEVENLABS_VOICE_ID_EN

  HEYGEN_API_KEY
  HEYGEN_TALKING_PHOTO_ID
  HEYGEN_VOICE_FR
  HEYGEN_VOICE_EN
  HEYGEN_VOICE_ES
  HEYGEN_VOICE_MULTI
  HEYGEN_MODE

  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

  STRIPE_PRICE_JUNIOR
  STRIPE_PRICE_OTHER
  STRIPE_PRICE_STAGE
  STRIPE_PRICE_GRADUATE
  STRIPE_PRICE_MID
  STRIPE_PRICE_MANAGER
  STRIPE_PRICE_EXEC
  STRIPE_PRICE_PACK3JUNIOR
  STRIPE_PRICE_PACK3MID
  STRIPE_PRICE_PACK5MIX
  STRIPE_PRICE_INTERNSHIP
  STRIPE_PRICE_JOB
  STRIPE_PRICE_CASE
  STRIPE_PRICE_PROMOTION
  STRIPE_PRICE_REVIEW
  STRIPE_PRICE_GOAL
  STRIPE_PRICE_MOBILITY
  STRIPE_PRICE_PRACTICE
  STRIPE_PRICE_STRATEGIC
)

for ENV in "${ENVIRONMENTS[@]}"; do
  echo "🔧 Adding variables for $ENV environment..."
  for VAR in "${VARS[@]}"; do
    echo "➕ Adding $VAR to $ENV..."
    vercel env add $VAR $ENV
  done
done

echo "🎉 DONE. Now redeploy with:"
echo "vercel --prod"
